Text File of DDL
-- MySQL Script generated by MySQL Workbench
-- Thu May  4 21:03:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mymobile
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mymobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mymobile` DEFAULT CHARACTER SET latin1 ;
USE `mymobile` ;
-- -----------------------------------------------------
-- Table `mymobile`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`customer` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`customer` (
  `customerID` INT(11) NOT NULL,
  `customerName` VARCHAR(50) NOT NULL,
  `streetAddress` VARCHAR(50) NOT NULL,
  `phoneNumber` VARCHAR(50) NOT NULL,
  `emailAddress` VARCHAR(50) NOT NULL,
  `DateOfBirth` DATE NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mymobile`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`plan` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`plan` (
  `planID` INT(11) NOT NULL,
  `planType` VARCHAR(50) NOT NULL,
  `planName` VARCHAR(50) NOT NULL,
  `planDuration` TIMESTAMP NOT NULL,
  `planCost` DECIMAL(10,2) NOT NULL,
  `planFeatures` TEXT NULL,
  PRIMARY KEY (`planID`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mymobile`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`transaction` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`transaction` (
  `transactionID` INT(11) NOT NULL,
  `transactionType` VARCHAR(50) NOT NULL,
  `transactionDate` DATE NOT NULL,
  `transactionAmount` DECIMAL(10,2) NOT NULL,
  `planID` INT(11) NOT NULL,
  `customerID` INT(11) NOT NULL,
  PRIMARY KEY (`transactionID`),
  CONSTRAINT `fk_transaction_plan1`
    FOREIGN KEY (`planID`)
    REFERENCES `classicmodels`.`plan` (`planID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `classicmodels`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_transaction_plan1_idx` ON `mymobile`.`transaction` (`planID` ASC) VISIBLE;
CREATE INDEX `fk_transaction_customer1_idx` ON `mymobile`.`transaction` (`customerID` ASC) VISIBLE;
-- -----------------------------------------------------
-- Table `mymobile`.`call_traffic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`call_traffic` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`call_traffic` (
  `callID` INT(11) NOT NULL,
  `callDate` DATE NOT NULL,
  `callDuration` TIMESTAMP NOT NULL,
  `callType` VARCHAR(50) NOT NULL,
  `callCost` DECIMAL(10,2) NOT NULL,
  `customerID` INT(11) NOT NULL,
  PRIMARY KEY (`callID`),
  CONSTRAINT `fk_call_traffic_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `classicmodels`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_call_traffic_customer1_idx` ON `mymobile`.`call_traffic` (`customerID` ASC) VISIBLE;
-- -----------------------------------------------------
-- Table `mymobile`.`customer_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`customer_plan` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`customer_plan` (
  `customerID` INT(11) NOT NULL,
  `planID` INT(11) NOT NULL,
  PRIMARY KEY (`customerID`, `planID`),
  CONSTRAINT `fk_customer_plan_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `classicmodels`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_plan_plan1`
    FOREIGN KEY (`planID`)
    REFERENCES `classicmodels`.`plan` (`planID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_customer_plan_customer1_idx` ON `mymobile`.`customer_plan` (`customerID` ASC) VISIBLE;
CREATE INDEX `fk_customer_plan_plan1_idx` ON `mymobile`.`customer_plan` (`planID` ASC) VISIBLE;
-- -----------------------------------------------------
-- Table `mymobile`.`cancellation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymobile`.`cancellation` ;
CREATE TABLE IF NOT EXISTS `mymobile`.`cancellation` (
  `cancellationID` INT(11) NOT NULL,
  `cancellationDate` DATE NOT NULL,
  `cancellationReason` TEXT NULL,
  `customerID` INT(11) NOT NULL,
  PRIMARY KEY (`cancellationID`),
  CONSTRAINT `fk_cancellation_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `classicmodels`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_cancellation_customer1_idx` ON `mymobile`.`cancellation` (`customerID` ASC) VISIBLE;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

